# application.yml
server:
  port: 8090

spring:
  datasource:
    url: "jdbc:mysql://${MSSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:stock}?createDatabaseIfNotExist=true"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD:}"
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update