# application.yml
server:
  port: 8090

spring:
  application:
    name: stock

  datasource:
    url: "jdbc:mysql://${MSSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:stock}?createDatabaseIfNotExist=true"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PASSWORD:}"
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_HOST:http://localhost:8070/eureka}
  instance:
    instance-id: "${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}"


---
spring:
  profiles: other
server:
  port: 8091
